### ISSUE TITLE
trained model checkpoint availability?

### ISSUE THREAD

**Issue by kieran-at-pieces** [MaitySubhajit/SelfDocSeg#3]
Do you plan to release a trained model checkpoint? Thanks!

**Comment by MaitySubhajit** [comment]
Hi!
There is no plan of checkpoint release as of now. However, given the queries regarding checkpoints we might plan for such release in future, although it will at least take a few months to do so. We shall be updating the same in this repository README. Please keep an eye on that.
Thank you!

**Comment by yellowjs0304** [comment]
@MaitySubhajit Hi, Thank you for sharing nice work.
Don't you still have any plan for sharing pre-trained checkpoint??

**Comment by wf1226448774** [comment]
+1
